---
format: html
editor: visual
filters: 
  - webr
title: "Introduction to GGPlot"
---

```{webr-r}
#| context: setup
#| label: input data

library(tidyverse)
library("palmerpenguins")
library(naniar)

penguin<- tibble('species'=penguins$species, 'island'=penguins$island, 'bill_length' = penguins$bill_length_mm, 'bill_depth' = penguins$bill_depth_mm, 'flipper_length'=penguins$flipper_length_mm, 'body_mass'=penguins$body_mass_g, 'year'=penguins$year, 'sex'=penguins$sex)

knitr::opts_chunk$set(error = TRUE)
knitr::opts_chunk$set(echo = TRUE)
```

## An Introduction to GGPlot

In this tutorial, we'll be looking at how to create plots using the package `ggplot`.

We'll start by learning about how `ggplot` works.

### Syntax

First, let's consider the syntax when we write code with ggplot. There are many commands that can be used within the `ggplot()` function. They are all connected using a `+`.

General syntax for `ggplot()`:

-   `ggplot(data, aes(x=variable1, y=variable2))` `+`

    `geom_x()` `+`

    `……`

    OR

-   `dataframe` `|>`

    `ggplot(aes(x=variable1, y=variable2))` `+`

    `geom_x()` `+`

    `……`

Specifying variables: X is the explanatory variable and Y is the outcome variable

### Aesthetics

Within ggplot code, you can specify the aesthetics with various variables including color, size, variables, number of bins (in a histogram), etc.

For example the following code specifies the x & y variables, point size & color:

`ggplot(dataframe, aes(x=month, y=temperature) + geom_point(size=5, color=red)`

### Geometry

You can then include geometry (lines, points, bar graph, scatterplot) including:

-   `geom_line()`: Connects all the points in a plot

-   `geom_smooth(method="lm", se=FALSE)`: Creates a line of best fit

-   `geom_point()`: Creates points (scatterplot) for each data point

-   `geom_bar()` : Creates a bar graph

    -   Syntax: `geom_bar(position="___")` Can choose "stack" (bars on top of each other), "dodge" (bars side by side) or "fill" (bars stacked, scaled to 100%).

-   `geom_col()`: Creates a bar graph with *pre-aggregated* data.

-   `geom_histogram()`: Creates a histogram

    -   Syntax: `geom_histogram(bins=X)` Specify number of bins

-   `geom_density()`: Creates a density graph

    -   Syntax: `geom_density(adjust=X)` X is a ratio, how smooth the graph is

-   `labs()` : Add a title and axes labels to your graph

-   And more!

## Other functions to use with GGplot

1.  `fct_infreq()`: Order data by its frequency.

    Syntax in ggplot: `ggplot(aes(x=fct_infreq(data)))` OR `ggplot(aes(y=fct_infreq(data)))`

2.  `fct_reorder()` : Reorder levels of a factor (or vector) based on the result of another function applied to all values within a specified variable.

    Syntax: `ggplot(aes(fct_reorder(factor, variable, .fun = function)))` The `.fun` default is median. That is, the function reorders the factor based on the median of the variable.

3.  `fct_collapse()` : Collapse factor levels into groups you define.

    Syntax: `fct_collapse(data, group1=value, group2=value)`

4.  `group_by()`: Used to group data by a specific variable.

5.  `facet_wrap()`: Create multiple graphs by group categories. Separate graphs wrapped around.

    Syntax: `facet_wrap(~facet + facet + facet...)` Note: can add more facets using a +

6.  `summarize()`: Displays a table with summary statistics you specify. Can also specify groups to group the data by.

    Syntax: `summarize(.data, summary statistic)`

## Our Dataset

We will work with a dataset with measurements for 3 different species of penguins on islands in the Palmer Archipelago, Antarctica. We'll be focusing on the measurements for species, location, bill length (mm), bill depth (mm), flipper length (mm), body mass (g), sex, and year the data was taken. Here's more [information](https://cran.r-project.org/web/packages/palmerpenguins/readme/README.html) about the [data set](https://cran.r-project.org/web/packages/palmerpenguins/readme/README.html)!

Here is a preview of the data you will be working with:

```{webr-r}
penguin
```

## Exercises

Here are some practice exercises. You can click for hints and the answer for each problem.

### Exercise 1

In this exercise, you will create 3 scatter plots, one for each species of penguin, displaying penguins' body mass and flipper length. Additionally include a line of best fit.

The different parts of this exercise will walk you through the process of tidying the data and creating the scatter plot.

#### Part A

First, let's clean the data and remove any rows with missing values. Create a new dataset called `penguin_clean` which doesn't contain NA values.

```{webr-r}
#Your code here

n_miss(penguin_clean) #If your code works, this should print 0. 
```

::: {.callout-tip collapse="true" icon="false"}
## Hint

```{webr-r}
penguin_clean<- na.omit(_____)
```
:::

::: {.callout-note collapse="true" icon="false"}
## Answer

```{webr-r}
penguin_clean<- na.omit(penguin)
```
:::

#### Part B

Now use your clean data to construct a scatterplot with `flipper_length` as the explanatory variable and `body_mass` as the outcome variable. Add a line of best fit.

```{webr-r}
#Your code here 

```

::: {.callout-tip collapse="true" icon="false"}
## Hint

You'll need to use ggplot, specify the data, the aesthetics (which includes the x and y variables) and then add a geometry to your plot to create points and a line of best fit.
:::

::: {.callout-tip collapse="true" icon="false"}
## Hint

```{webr-r}

ggplot(_______, aes(x=____, y=____))+
  geom_point()+ 
  geom_smooth(method=_____, se=FALSE)
```
:::

::: {.callout-note collapse="true" icon="false"}
## Answer

```{webr-r}
ggplot(penguin_clean, aes(x=flipper_length, y=body_mass))+
  geom_point()+ 
  geom_smooth(method="lm", se=FALSE)
```
:::

#### Part C

Finally, let's separate the plot into 3 different plots, one for each species.

```{webr-r}
#Your code here 
 

```

::: {.callout-tip collapse="true" icon="false"}
## Hint

Use the function `facet_wrap()` and be sure to define your facet.
:::

::: {.callout-tip collapse="true" icon="false"}
## Hint

```{webr-r}
# Use facet_wrap(~_____$_____)
```
:::

::: {.callout-note collapse="true" icon="false"}
## Answer

```{webr-r}
ggplot(penguin_clean, aes(x=flipper_length, y=body_mass))+
  geom_point()+ 
  geom_smooth(method="lm", se=FALSE)+ 
  facet_wrap(~penguin_clean$species)
```
:::

### Exercise 2

Create a bar graph displaying the mean bill length for each species of penguin.

#### Part A

First, we need to make our data tiny so that we can then input it into a function. So, start by using the `summarize()` function to display the mean bill length of penguins by species.

```{webr-r}
#Your code here


#If your code works, you should see the mean bill length of each penguin species. 
```

::: {.callout-tip collapse="true" icon="false"}
## Hint

In addition to the `summarize()` function, you'll need to also use the `group_by()` function to group by species. Use the pipe to use both of these functions together.
:::

::: {.callout-tip collapse="true" icon="false"}
## Hint

```{webr-r}
penguin_clean |> 
group_by(_____)|> 
  summarize(mean_bill=__________)
```
:::

::: {.callout-note collapse="true" icon="false"}
## Answer

```{webr-r}
penguin_clean |> 
group_by(species)|> 
  summarize(mean_bill=mean(bill_length))
```
:::

#### Part B

Now that the data is tidy and tiny, we can plot it. Add to your code from part A and create a bar graph.

::: {.callout-tip collapse="true" icon="false"}
## Hint

Recall: `geom_bar()` is used when the data still needs to be aggregated.

`geom_col()` is used when the data is already aggregated.
:::

::: {.callout-tip collapse="true" icon="false"}
## Hint

```{webr-r}
penguin_clean |> 
  group_by(species)|> 
  summarize(mean_bill=mean(bill_length)) |> 
  ggplot(aes(x=____, y=_____)) +
  geom_col()
```
:::

::: {.callout-note collapse="true" icon="false"}
## Answer

```{webr-r}
penguin_clean |> 
  group_by(species)|> 
  summarize(mean_bill=mean(bill_length)) |> 
  ggplot(aes(x=species, y=mean_bill)) +
  geom_col()
```
:::

#### Part C

Finally, we want to order the columns in the bar graph from smallest to largest. To do this, we'll use `fct_reorder()`. Find where it goes in your current code. Hint: You will not have to write a new line.

Feel free to also add other features to your graph, like a title, colored bars, etc!

::: {.callout-tip collapse="true" icon="false"}
## Hint

What are you trying to reorder on the graph? Are you trying to reorder the x variable or y variable?
:::

::: {.callout-tip collapse="true" icon="false"}
## Hint

```{webr-r}
penguin_clean |> 
  group_by(species)|> 
  summarize(mean_bill=mean(bill_length)) |> 
  ggplot(aes(x=fct_reorder(_____, _____), y=mean_bill))+
  geom_col()
```
:::

::: {.callout-note collapse="true" icon="false"}
## Answer

```{webr-r}
penguin_clean |> 
group_by(species)|> 
  summarize(mean_mass=mean(body_mass))|>
ggplot(aes(x=fct_reorder(species, mean_mass), y=mean_mass))+
  geom_col()
```
:::
