---
format: html
editor: visual
filters: 
  - webr
title: "Introduction to stringr Package"
---

```{webr-r}
#| context: setup
#| label: input data

library(tidyverse)
library("palmerpenguins")

penguin<- tibble(penguins$species, penguins$island, penguins$bill_length_mm, penguins$body_mass_g, penguins$year)
penguin_sample<- na.omit(penguin)
penguin_sample<- rename(penguin_sample, species =`penguins$species`, location = `penguins$island`, bill_length = `penguins$bill_length_mm`, body_mass = `penguins$body_mass_g`, year = `penguins$year`)
penguin_sample$location<- paste(penguin_sample$location,"Palmer Archipelago, Antarctica", sep=", ")

knitr::opts_chunk$set(error = TRUE)
knitr::opts_chunk$set(echo = TRUE)
```

## Welcome

In this tutorial, you will delve into the manipulation of text data with the `stringr` package in the tidyverse. Text data is ubiquitous and manipulating strings efficiently is a fundamental skill in data analysis. `stringr` provides a cohesive set of functions designed to make string manipulation easy and consistent.

### Functions in Focus

Let's familiarize ourselves with the essential functions from `stringr` that we'll explore in this tutorial, along with their syntax:

1.  `str_sub()`: This function allows you to extract substrings in a character vector.

Syntax: `str_sub(string, start_position, end_position)`

2.  `str_to_lower()`: Use this function to transform text to all lowercase.

Syntax: `str_to_lower(string)`

3.  `word()`: This function will extract a specific word from a string (or character vector). 

Syntax: `word(string, start, end, sep=fixed("___"))`

4.  `str_remove()`: Use `str_remove()` to eliminate the first instance of a pattern in a string.

Syntax: `str_remove(string, pattern)`

5. `str_length()`: This function will give the number of *characters* in each element of a character vector. 

Syntax: `str_length(string)`

6. `str_detect()`: This function will look at each element of a string and determine if it matches a given pattern. For each element, it will output `FALSE` or `TRUE` depending on whether it matches the pattern. 

Syntax: `str_detect(string, pattern)`

With these tools at your disposal, you'll be able to tackle a wide array of text processing tasks. Let's proceed to the exercises and start putting these functions to work!

## Our Dataset

We will work with a dataset with size measurements for 3 different species of penguins on islands in the Palmer Archipelago, Antarctica. We'll be focusing on the measurements for bill length (mm), body mass (g), as well as the location and year the data was taken. Here's more [information](https://cran.r-project.org/web/packages/palmerpenguins/readme/README.html) about the [data set](https://cran.r-project.org/web/packages/palmerpenguins/readme/README.html)!

Here is a preview of the data you will be working with:

```{webr-r}
penguin_sample
```

## Exercises

Here are some practice exercises. You can click for hints and the answer for each problem.

### Exercise 1

Create a variable called `location_lower` that converts location in the `penguin_sample` data frame to lowercase using `str_to_lower()`.

```{webr-r}
#| autorun: false
#| message: FALSE
# Your code here

str(penguin_sample$location_lower) # this code will run successfully and show a few example values in lower case if the variable was properly created
```

::: {.callout-tip collapse="true" icon="false"}
## Hint

Use the str_to_lower function on the 'location' column of 'penguin_sample'.
:::

::: {.callout-tip collapse="true" icon="false"}
## Hint

```{webr-r}
penguin_sample$location_lower <- str_to_lower(penguin_sample$_____)
```
:::

::: {.callout-note collapse="true" icon="false"}
## Answer

```{webr-r}
penguin_sample$location_lower <- str_to_lower(penguin_sample$location)
```
:::

### Exercise 2

Sometimes we may decide the input in one observation is too long. Use `str_length()` to check how many characters there are in the *first* entry of the `location` column in our `penguin_sample` data set. 

```{webr-r}
# Your code here


#If your code worked, you should see that there are 41 characters in the first entry of the location column. 
```

::: {.callout-tip collapse="true" icon="false"}
## Hint

Use the str_length() function to count the number of characters in each entry of a vector. Then use bracket notation to indicate the first entry. 

:::

::: {.callout-tip collapse="true" icon="false"}
## Hint

```{webr-r}
str_length(____$____)[___]
```
:::

::: {.callout-note collapse="true" icon="false"}
## Answer

```{webr-r}
str_length(penguin_sample$location)[1]
```
:::

### Exercise 3

Split the Island variable in the `penguin_sample` data frame into separate elements using the `word()` based on the comma seperator. In particular, create a new column called `island` that extracts only the island name (without Palmer Archipelago, Antarctica).

```{webr-r}
#| autorun:false
# Your code here

str(penguin_sample$island) # if your code worked, you should see your new island variable with this code
```

::: {.callout-tip collapse="true" icon="false"}
## Hint

Use the word() function and specify the comma as the separator. Extract the first word by specifying where the start.
:::

::: {.callout-tip collapse="true" icon="false"}
## Hint

```{webr-r}
#| autorun: false
penguin_sample$island <- word(______$______, start=___, sep="___")
```
:::

::: {.callout-note collapse="true" icon="false"}
## Answer

```{webr-r}
#| autorun: false
penguin_sample$island <- word(penguin_sample$location, start=1, sep=",")
```
:::


### Exercise 4

Create a new variable called `location_short` that removes the phrase "Antarctica" from all locations in the `penguin_sample` data frame using `str_remove()`.

```{webr-r}
# Your code here

str(penguin_sample$location_short) # if your code worked, this code will show you the structure of your new variable

```

::: {.callout-tip collapse="true" icon="false"}
## Hint

The str_remove function needs a pattern to match what should be removed.
:::

::: {.callout-tip collapse="true" icon="false"}
## Hint

```{webr-r}
penguin_sample$location_short <- str_remove(__$___, "_____")
```
:::

::: {.callout-note collapse="true" icon="false"}
## Answer

```{webr-r}
penguin_sample$location_short <- str_remove(penguin_sample$location, ", Antarctica")
```
:::

### Exercise 5

Let's check your work on Exercise 4. Use `str_detect()` to check all the values in your `location_short` column and ensure that "Antarctica" does not appear in any of the entries in that column (or string).

```{webr-r}
#Your code here 


#If your code worked, you should see a long list of FALSE values indicating that "Antarctica" does not appear in any entry.
```

::: {.callout-tip collapse="true" icon="false"}
## Hint

```{webr-r}
str_detect(____$_____, "____")
```
:::

::: {.callout-note collapse="true" icon="false"}
## Answer

```{webr-r}
str_detect(penguin_sample$location_short, "Antarctica")
```
:::

### Exercise 6

Create a variable called `year_short` that extracts the last two characters of the year using `str_sub()`.

```{webr-r}
# Your code here

str(penguin_sample$year_short) # The year should only display the last two numbers
```

::: {.callout-tip collapse="true" icon="false"}
## Hint

Use str_sub(). -1 will stand in for the last character.
:::

::: {.callout-tip collapse="true" icon="false"}
## Hint

```{webr-r}

penguin_sample$year_short <- str_sub(____, ____, ____)

```
:::

::: {.callout-note collapse="true" icon="false"}
## Answer

```{webr-r}
penguin_sample$year_short <- str_sub(penguin_sample$year, 3, -1)

```
:::

Congratulations, you finished this tutorial!
